### PR TITLE
Delete IconCard from component library. 

### PR DESCRIPTION
**Pull request by wittejm**
This is not used anywhere in letters-mobile and Liz recommended it be deleted.

### CODE REVIEW

**Review by cainlevy — APPROVED** [review]

**Comment by gabrielsaruhashi** [comment]
@wittejm wait! we shouldn't delete this. It's used on connect-mobile I bleieve

**Review by gabrielsaruhashi — CHANGES_REQUESTED** [review]
blocking this! it requires coordination with Connect Mobile

**Comment by cainlevy** [comment]
@gabrielsaruhashi i assumed this library version was dedicated to letters mobile. do you think we'll pull all of these brand changes into connect mobile as well? when do we split them up to avoid forced lockstep upgrades?

**Comment by wittejm** [comment]
^^ I also was under the impression these library changes are meant only to support Letters.

**Comment by gabrielsaruhashi** [comment]
sorry, good point! I jumped the gun here
I chatted with @wittejm , and I just want to make sure we don't bump the version on the Connect mobile side!
Whenever I need to make changes on the comp lib, I'll just move them over to the other repo.

**Review by gabrielsaruhashi — APPROVED** [review]

**Pull request merged**
